version: '3.5'
services:
  sumo-docker:
    image: kensukemi/sumo-ubuntu18
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./mount_dir:/mount_dir
    stdin_open: true
    tty: true
    container_name: sumo-docker-dev
