version: 2.1

orbs:
  python: circleci/python@1.2
  win: circleci/windows@2.2.0

jobs:
  linux:
    machine: true
    steps:
      - checkout
      - run:
          name: Installing OpenSSL
          command: sudo apt update && sudo apt install OpenSSL
      - run:
          name: Updating Pyenv
          command: cd /opt/circleci/.pyenv/plugins/python-build/../.. && git pull && cd -
      - run:
          name: Install Python
          command: pyenv install miniconda3-4.7.12
      - run:
          name: Set Python Version
          #
          command: pyenv global miniconda3-4.7.12
      - run:
          name: install package dependencies
          command: pip install poetry && make install && pip install pytest pytest-resource-path
      - run:
          name: Run tests
          command: make test
#  windows:
#    executor:
#      name: win/default
#    steps:
#      - run:
#         command: python -V
#         shell: bash.exe
#      - run:
#          name: install package dependencies
#          command: pip install poetry && poetry install && poetry build --format sdist && tar -xvf dist/*-`poetry version -s`.tar.gz && cd sumo_tasks_pipeline-* && pip install -e .
#          shell: bash.exe
#      - run:
#          command: pip install pytest pytest-resource-path
#          shell: bash.exe
#      - run:
#          name: Run tests
#          command: pytest tests && pytest example_script.py
#          shell: bash.exe
workflows:
  tests:
    jobs:
      - linux
